Lib refactoring
emspay/ems-online-virtuemart pull request #13
Opened 2020-09-15 15:36 UTC by LeasoftKonstantinShapoval

2020-09-30 08:29 UTC, tiutiunnykleasoft requested changes
If Afterpay switched off other payment doesnt works. 
Also on return url need corrections

2020-10-07 10:40 UTC, tiutiunnykleasoft commented
1. in `plgVmConfirmedOrder` method: $cart is not using - should remove it?.
2. for method `usersFromAllowedCountries` method must be updated PHPcomments.
3. The error with unworked payments when Afterpay is switched off is still present.
4. https://github.com/emspay/ems-online-virtuemart/pull/13#discussion_r497300909

2020-10-12 10:48 UTC, LeasoftKonstantinShapoval commented
@tiutiunnykleasoft  Re review please.

2020-10-12 12:47 UTC, tiutiunnykleasoft reviewed
fix

2020-10-12 12:47 UTC, tiutiunnykleasoft commented on libraries/emspay/Emspay/Lib/EmspayVmPaymentPlugin.php
> +     * fetch vm order number form hte payment table
drunk comment

2020-10-12 12:47 UTC, tiutiunnykleasoft commented on plugins/vmpayment/emspayafterpay/emspayafterpay.php
> +        if(!$cart->cartData['paymentName'] = 'AfterPay'){
Hint:
`=` declare the variable.
`==` compares values.

2020-10-12 12:59 UTC, LeasoftKonstantinShapoval commented
Fixed and refactored.

2020-10-12 15:36 UTC, tiutiunnykleasoft requested changes
Mostly OK. But still, see order number of finish page

2020-10-13 12:06 UTC, LeasoftKonstantinShapoval commented
order_id removed

2020-10-15 08:26 UTC, LeasoftKonstantinShapoval commented
Updated

2020-10-15 11:17 UTC, tiutiunnykleasoft commented on plugins/vmpayment/emspayamex/emspayamex.php
> +    public function plgVmOnPaymentResponseReceived(&$html, &$payment_reponse)
Update PHPdoc in this and other payments

2020-10-15 11:19 UTC, tiutiunnykleasoft commented on plugins/vmpayment/emspaypaypal/emspaypaypal.php
> -            $html .= "<p>". JText::_('EMSPAY_LIB_THANK_YOU_FOR_YOUR_ORDER'). "</p>";
Remove `EMSPAY_LIB_THANK_YOU_FOR_YOUR_ORDER` from the languages translation files

2020-10-15 12:52 UTC, LeasoftKonstantinShapoval commented
@tiutiunnykleasoft Do we need add some notification to Changelog?

2020-10-15 12:54 UTC, tiutiunnykleasoft commented
> @tiutiunnykleasoft Do we need add some notification to Changelog?

@LeasoftKonstantinShapoval yes

2020-10-15 12:59 UTC, LeasoftKonstantinShapoval commented
> @LeasoftKonstantinShapoval yes

Something like "Fixes bug with wrong call after return url."?

2020-10-16 07:18 UTC, LeasoftKonstantinShapoval commented
Updated.

2020-10-19 11:05 UTC, tiutiunnykleasoft commented
Great work!
Actually, we must display the "Thank you message" only if payment completed! As I can see in `apple-pay` and other payment, when order returned with "new" status, we display "Thank you page", is it correct for you?
At this moment I can't approve changes until we do not end the discussion of that question.

2020-10-19 11:11 UTC, LeasoftKonstantinShapoval commented
> As I can see in apple-pay and other payment, when order returned with "new" status, we display "Thank you page", is it correct for you?
Yes. it is.

2020-10-19 11:13 UTC, tiutiunnykleasoft commented
> > As I can see in apple-pay and other payment, when order returned with "new" status, we display "Thank you page", is it correct for you?
> 
> Yes. it is.

In this case, what do we thank the user for?)

2020-10-19 11:16 UTC, LeasoftKonstantinShapoval commented
For patience. :)

2020-10-19 11:20 UTC, tiutiunnykleasoft commented
> For patience. :)

Good idea :)
Could the user have misunderstandings with the store due to the message
"Thank you for your Order!
Paid with аpple-pay "?

When in fact he changed his mind or was unable to pay.

2020-10-19 11:27 UTC, LeasoftKonstantinShapoval commented
> Could the user have misunderstandings with the store due to the message
> "Thank you for your Order!
> Paid with аpple-pay "?

Of course, and this bug stands not only in VirtueMart. But earlier I ask for this and got answer 'Its a feature'.

2020-10-19 11:28 UTC, tiutiunnykleasoft commented
> > Could the user have misunderstandings with the store due to the message
> > "Thank you for your Order!
> > Paid with аpple-pay "?
> 
> Of course, and this bug stands not only in VirtueMart. But earlier I ask for this and got answer 'Its a feature'.

Can you send a link to this question if you has ?

2020-10-19 11:33 UTC, LeasoftKonstantinShapoval commented
> Can you send a link to this question if you has ?

It was in skype or in voice chat, or in office.

2020-10-19 11:36 UTC, LeasoftKonstantinShapoval commented
We can start new task and fix this.
What do you think?

2020-10-19 11:40 UTC, LeasoftKonstantinShapoval commented
` case 'new':
                $this->updateOrderStatus($this->methodParametersFactory()->statusNew(), $virtuemart_order_id);
                return true;`
https://github.com/emspay/ems-online-virtuemart/blob/8b5efb7cbe0857873d90c41b9a5713017671a5b8/libraries/emspay/Emspay/Lib/EmspayVmPaymentPlugin.php#L192

I think its happening because we got status 'new' as true in status response.

2020-10-19 11:42 UTC, tiutiunnykleasoft commented
> `case 'new': $this->updateOrderStatus($this->methodParametersFactory()->statusNew(), $virtuemart_order_id); return true;`
> 
> https://github.com/emspay/ems-online-virtuemart/blob/8b5efb7cbe0857873d90c41b9a5713017671a5b8/libraries/emspay/Emspay/Lib/EmspayVmPaymentPlugin.php#L192
> 
> I think its happening because we got status 'new' as true in status response.

Look like it.

2020-10-19 12:10 UTC, tiutiunnykleasoft approved these changes

2020-10-19 13:08 UTC, merged